### ISSUE TITLE
Remove warnings

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-events-ios#30] opened 2018-01-06 00:10 UTC
In mapbox-navigation-ios, we have quite a few warnings that seemed to come about after upgrading to Swift 4.

![image](https://user-images.githubusercontent.com/1058624/34633730-e6c0f7ca-f232-11e7-951a-4facdc4f624c.png)

It'd be great to this list down a bit.

**Comment by boundsj** [comment] 2018-01-06 00:21
Thanks! 

I'm closing this as a dupe of what was fixed in https://github.com/mapbox/mapbox-events-ios/pull/20.

Also a commit in #27 (https://github.com/mapbox/mapbox-events-ios/pull/27/commits/566846a029994d811d1c0fb1bdb73020d6613d80) fixes the warning about `NSProcessInfoPOwerStateDidChangeNotification` and `SecKeyCopyExternalRepresentation`.

We are focused on #27 since it is required to ship the standalone telem library in our Maps SDK for iOS. Once that lands and we ship in the maps SDK, we will make another release of this library with the fixes for these warnings. In the meantime, there is no risk of a crash in a client app because of this.

**Closed as completed by boundsj** 2018-01-06 00:21 UTC
